fix sorting
bcgov/zeva pull request #1234
Opened 2022-12-13 17:36 UTC by vibhiquartech

2022-12-13 20:10 UTC, AlexZorkin requested changes
Please take a look at the Administrative Credit Reduction transaction type in the transactions list. It is not showing the correct amounts in the balance column. Also please check the purchase agreement transaction type for correct balances using test data. Prod does not have any purchase agreement transactions yet but may in the future.

Last thing, when submitting prs please follow the PR naming conventions ex. Fix: Transaction Table Sorting - ZEVA 492

2022-12-13 20:51 UTC, vibhiquartech commented
Please verify the updated changes @AlexZorkin

2022-12-13 21:26 UTC, AlexZorkin requested changes

2022-12-13 21:26 UTC, AlexZorkin commented on frontend/src/credits/components/CreditTransactionListTable.js
> +  transactions.sort((a, b) => {
These two sorts can be combined and then remove the console.log(transactions) and we're good to go. thanks

2022-12-14 17:21 UTC, AlexZorkin approved these changes

2022-12-14 17:21 UTC, merged