Zelda 581 - Error types count added to credit application
bcgov/zeva pull request #1253
Opened 2023-01-03 17:11 UTC by vibhiquartech

2023-01-05 23:07 UTC, AlexZorkin requested changes
looks good, just one minor fix

2023-01-05 23:07 UTC, AlexZorkin commented on backend/api/viewsets/credit_request.py
> +        errorKey, eorroCounts = np.unique(newErrorList, return_counts=True)
slight spelling mistake eorroCounts should be errorCounts

2023-01-06 00:49 UTC, vibhiquartech commented on backend/api/viewsets/credit_request.py
> +        errorKey, eorroCounts = np.unique(newErrorList, return_counts=True)
Made changes as requested for spelling errorCounts

2023-01-06 21:52 UTC, AlexZorkin approved these changes

2023-01-06 21:55 UTC, merged