ZEVA-1367- Disable editing opening credit balances
bcgov/zeva pull request #1419
Opened 2023-02-17 22:06 UTC by vibhiquartech

2023-02-17 22:36 UTC, emi-hi requested changes
it looks like the opening balance is referenced 4 times in the code, twice (a and b) as you updated here, but theres also a separate case if no prior year balance exists, so theres an a and b there as well that needs to also be read only. Its just a little bit further down in the code (the input box starts at line 431 and the readonly line is 453 for A credits. B credits is after that.)

The other thing is in the meeting we just had with the PO, you agreed to make this plain text rather than a disabled input box. Please makes these changes for all 4 cases and then it can be merged in.

2023-02-18 00:02 UTC, AlexZorkin requested changes
use the following method instead of the ternary operations:

This ternary is fairly redundant so let's use a method like the following instead:
const getSupplementalValue = (modelYear, creditAorBText) => {
  // creditAorB is either 'A' or 'B'
  const creditType = `credit${creditAorBText}Value`
  const newData = getNewData('creditBalanceStart', modelYear, creditType)
  if (newData == '' || newData == null) {
    formatNumeric(creditBalanceStart[modelYear][creditAorBText], 2)
  } else {
    return formatNumeric(newData)
  }
}

2023-02-18 00:02 UTC, AlexZorkin commented on frontend/src/compliance/components/ComplianceObligationTableCreditsIssued.js
> +                        ? formatNumeric(creditBalanceStart[each].A, 2)
This ternary is fairly redundant so let's use a method like the following instead:
const getSupplementalValue = (modelYear, creditAorBText) => {
  // creditAorB is either 'A' or 'B'
  const creditType = `credit${creditAorBText}Value`
  const newData = getNewData('creditBalanceStart', modelYear, creditType)
  if (newData == '' || newData == null) {
    formatNumeric(creditBalanceStart[modelYear][creditAorBText], 2)
  } else {
    return formatNumeric(newData)
  }
}

2023-02-21 21:28 UTC, AlexZorkin approved these changes

2023-02-21 21:31 UTC, merged