Fix - Reassessment/Supplementary Report Timeline #1868
bcgov/zeva pull request #1920
Opened 2023-08-14 22:06 UTC by JulianForeman

- Modified logic to exclude supplemental report from the reporting timeline if a reassessment has started for it

2023-08-15 20:43 UTC, tim738745 requested changes

2023-08-15 20:43 UTC, tim738745 commented on backend/api/viewsets/model_year_report.py
> +                    for re_report in supplemental_reports:
I think the case we're trying to deal with here is simply when a supplier submits a supplementary, and the govt then recommends/assesses it. So that will create two records in the SupplementaryReports table, one with a status of submitted, and another with a status of recommended or assessed, and we want to exclude the submitted one. I think it would be cleaner to just do something like this inside the for loop (line 340):

`

           if report.status.value in ["DRAFT", "RETURNED"] and (
                request.user.is_government and not report.is_reassessment
            ):
                exclude_supplemental_reports.append(report.id)

            if report.is_reassessment:
                if (
                    report.status.value not in ["ASSESSED", "REASSESSED"]
                    and not request.user.is_government
                ):
                    exclude_supplemental_reports.append(report.id)
            else:
                if request.user.is_government and report.status.value == 'SUBMITTED':
                    next_report = SupplementalReport.objects.filter(supplemental_id=report.id).exclude(status=ModelYearReportStatuses.DELETED).first()
                    if next_report and next_report.is_reassessment:
                        exclude_supplemental_reports.append(report.id)`

2023-08-16 21:06 UTC, JulianForeman commented on backend/api/viewsets/model_year_report.py
> +                    for re_report in supplemental_reports:
Didn't think about this solution, I implemented it.

2023-08-16 21:18 UTC, tim738745 approved these changes

2023-08-16 21:19 UTC, merged