Feat: Returned Model Year Report Information #1276
bcgov/zeva pull request #2028
Opened 2023-10-31 22:54 UTC by JulianForeman

- Adding display field to some report tables to allow reports to be returned, not show analyst adjustments and soft retain information

2023-10-31 23:23 UTC, tim738745 requested changes

2023-10-31 23:23 UTC, tim738745 commented on backend/api/viewsets/model_year_report.py
> +            ModelYearReportAssessmentComment.objects.filter(
display is set to 'false' here for ModelYearAssessmentComment, but the display field is never read, meaning that analysts would still see old assessment comments after re-submission?  Perhaps we should confirm this and if this is the case, then we could address this is in the frontend (AssessmentContainer.js)

2023-11-06 18:52 UTC, JulianForeman commented on backend/api/viewsets/model_year_report.py
> +            ModelYearReportAssessmentComment.objects.filter(
Confirmed the logic, and I added a bit to not display the assessment comments if the report is returned and then re-submitted.

2023-11-06 20:16 UTC, tim738745 requested changes

2023-11-06 20:16 UTC, tim738745 commented on backend/api/migrations/0004_auto_20231024_0908.py
> +        migrations.AlterField(
Looks good, just one last thing: I noticed the backend unit tests failing, and I tried it out and realized that it's because of some of these "AlterField" migrations. These migrations are being created because we upgraded the Django version a few releases ago, and the primary key + foreign key fields of our tables are being changed from AutoField to BigAutoField. This is fine and shouldn't be a breaking change, but I think what's happening is we have a legacy "AccountBalance" model, and because of a setting on the model, its foreign keys can't be updated to type BigAutoField. What I suggest we do right now is we remove the "AlterField" migrations and just keep the "AddField" migrations that are a result of the changes you made to the models (so remove lines 34 to 463). We can address these AlterField migrations later, and probably fix the current problem by removing the AccountBalance table entirely.

2023-11-07 18:01 UTC, tim738745 approved these changes

2023-11-07 18:01 UTC, merged