Fix: Report Returned Fixes #1276
bcgov/zeva pull request #2050
Opened 2023-11-08 19:07 UTC by JulianForeman

- Added logic to not display assessment comments, radio button selections or penalty amounts when a report is returned

2023-11-08 19:10 UTC, tim738745 approved these changes

2023-11-08 19:14 UTC, tim738745 requested changes

2023-11-08 19:14 UTC, tim738745 commented on backend/api/serializers/model_year_report.py
> +            return obj.get_ldv_sales() or obj.ldv_sales()
This change is causing a unit test to fail: 
File "/github/workspace/api/tests/test_model_year_reports.py", line 71, in test_assessment_patch_response ... 
File "/github/workspace/api/serializers/model_year_report.py", line 118, in get_ldv_sales
    return obj.get_ldv_sales() or obj.ldv_sales()
TypeError: 'NoneType' object is not callable

So either the unit test has to be updated or we have to reconsider this change

2023-11-14 19:37 UTC, JulianForeman commented on backend/api/serializers/model_year_report.py
> +            return obj.get_ldv_sales() or obj.ldv_sales()
I undid this change so the test should pass.

2023-11-14 22:00 UTC, tim738745 approved these changes

2023-11-14 22:00 UTC, tim738745 commented
@JulianForeman just needs to be rebased into 1.55.0

2023-11-14 22:09 UTC, closed without merging