Task: Reassessment Credit Modifications #2195
bcgov/zeva pull request #2214
Opened 2024-08-14 17:41 UTC by JulianForeman

- Allowing all credit fields to me modified in reassessments
- Added checks for empty values to avoid errors

2024-08-14 18:18 UTC, tim738745 requested changes

2024-08-14 21:55 UTC, JulianForeman commented on frontend/src/supplementary/components/CreditActivity.js
> +                              {creditA && AgetAssociatedDeduction(deduction, deductions)
Yes I did haha

2024-08-15 21:03 UTC, JulianForeman commented
> Also, @JulianForeman, just wondering if you tested making changes to the newly unlocked credit fields in a reassessment and submitting the reassessment? And upon director issuance, is the supplier's credit balance updated? Thanks!

The process seems to work 100% through saving, submitting and issuing the reassessment. I'm not too sure how to read the credit balances so I can't say for certain or not.

2024-08-16 00:06 UTC, tim738745 requested changes

2024-08-16 00:06 UTC, tim738745 commented on frontend/src/supplementary/components/CreditActivity.js
> +                              {creditB && getAssociatedDeduction(deduction, deductions)
Just one more here; should be: `getAssociatedDeduction(deduction, deductions).creditB && getAssociatedDeduction(deduction, deductions).creditB.eq(bigZero)`

2024-08-16 00:06 UTC, tim738745 commented
> > Also, @JulianForeman, just wondering if you tested making changes to the newly unlocked credit fields in a reassessment and submitting the reassessment? And upon director issuance, is the supplier's credit balance updated? Thanks!
> 
> The process seems to work 100% through saving, submitting and issuing the reassessment. I'm not too sure how to read the credit balances so I can't say for certain or not.

Ok, thanks!

2024-08-19 19:12 UTC, tim738745 approved these changes

2024-08-19 19:12 UTC, merged