2339 - Fix tab/stage-name inconsistency during loading issue
bcgov/zeva pull request #2402
Opened 2024-12-18 22:02 UTC by rogerlcleung

2025-01-02 22:23 UTC, tim738745 requested changes

2025-01-02 22:23 UTC, tim738745 commented on frontend/src/compliance/AssessmentContainer.js
>  const AssessmentContainer = (props) => {
Just wondering if there is a reason why we don't pass the `year` to `AssessmentContainer` via `ComplianceReportTabs` like we do for the other containers?

2025-01-02 23:24 UTC, rogerlcleung commented on frontend/src/compliance/AssessmentContainer.js
>  const AssessmentContainer = (props) => {
Currently (before the changes), when clicking on the Summary page or the Assessment page, the tabs will disappear during loading. Therefore, the original "inconsistent tab name during loading" issue can only be observed when navigating between the first three tabs, but not the Summary page and the Assessment page. After discussing with Lalita and Shaylene, we agreed that the inconsistency between this appearing/disappearing of the tabs should not occur in the Summary page. Fixing this was included in this PR. The layout of the Assessment page is different as there are other things on top of the tabs. In this case, keeping the tabs disappeared during loading might make sense. We agreed to leave this behaviour as in for the Assessment page as this would need more thoughts on the correct behaviour.

Passing the "year" to the containers is only required for the container to determine the displayed tab names during loading. Since the tabs will not be appeared when loading the Assessment page, I decided to leave the Assessment page untouched. If later we come up with a new behaviour for loading up this page, we can modify the code to fit the needs at that time.

2025-01-03 00:03 UTC, rogerlcleung commented on frontend/src/app/routes/Compliance.js
> +export const insertIdAndYear = (route, id, modelYear) => {
Done.

2025-01-03 18:13 UTC, tim738745 approved these changes

2025-01-03 18:13 UTC, merged